import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import { EVENT_TYPES } from '../../consts/consts';
import { IPlayerMove } from '../../models/IPlayerMove.interface';
import { ISocketMessage } from '../../models/ISocketMessage.interface';
import { WSService } from '../../services/WS.service';
import { fetchCount } from './gameApi';

export interface GameState {
  gameTable: string[][];
  gameOver: boolean;
  winner: string | undefined;
  currentPlayer: 'X' | 'O';
  numberOfMoves: number;
}

const initialState: GameState = {
  gameTable: [['', '', ''], ['', '', ''], ['', '', '']],
  gameOver: false,
  winner: undefined,
  currentPlayer: 'X',
  numberOfMoves: 0,
};

export const updateGameStateAsync = createAsyncThunk(
  'counter/updateGameState',
  async (amount: number) => {
    const response = await fetchCount(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const gameSlice = createSlice({
  name: 'game',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    makeMove: (state, action: PayloadAction<IPlayerMove>) => {
      const { moveRow, moveCol } = action.payload;
      if (state.gameTable[moveRow][moveCol] === '') {
        state.gameTable[moveRow][moveCol] = state.currentPlayer;
        state.currentPlayer = state.currentPlayer === 'X' ? 'O' : 'X';
        state.numberOfMoves += 1;
        const message: ISocketMessage<string[][]> = {
          type: EVENT_TYPES.PLAYER_MOVED,
          payload: state.gameTable
        }
        WSService.getInstance().sendMessage(message);
      }
    },
    restartGame: (state) => {
      state.currentPlayer = initialState.currentPlayer;
      state.gameTable = initialState.gameTable;
      state.gameOver = initialState.gameOver;
      state.numberOfMoves = initialState.numberOfMoves;
      state.winner = initialState.winner;
    },
    serverGameUpdate: (state, payload: PayloadAction<GameState>) => {
      debugger;
      state = payload.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(updateGameStateAsync.fulfilled, (state, action) => {
      });
  },
});

export const { makeMove, restartGame, serverGameUpdate } = gameSlice.actions;

export const selectCurrentPlayer = (state: RootState) => state.game.currentPlayer;
export const selectCurrentGameBoard = (state: RootState) => state.game.gameTable;
export const selectIsGameOver = (state: RootState) => state.game.gameOver === true;
export const selectWinner = (state: RootState) => state.game.winner;
export const selectNumberOfMoves = (state: RootState) => state.game.numberOfMoves;

export default gameSlice.reducer;
